"""add_consecutive_days_and_last_entry_date

Revision ID: 126d59924a35
Revises: b05bddddfde8
Create Date: 2026-02-21 00:31:37.700438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126d59924a35'
down_revision = 'b05bddddfde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_entry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('last_entry_date')
        batch_op.drop_column('consecutive_days')

    # ### end Alembic commands ###
