"""add_category_segments

Revision ID: 2f4e866d48f7
Revises: 1e17dacf628a
Create Date: 2026-02-20 20:51:42.192702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4e866d48f7'
down_revision = '1e17dacf628a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_ai_extractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_segments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_ai_extractions', schema=None) as batch_op:
        batch_op.drop_column('category_segments')

    # ### end Alembic commands ###
