"""add_ai_name_to_user_profile

Revision ID: 4e0d70019bb4
Revises: 2f4e866d48f7
Create Date: 2026-02-20 21:33:36.423189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0d70019bb4'
down_revision = '2f4e866d48f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('ai_name')

    # ### end Alembic commands ###
