"""add_cognitive_distortions

Revision ID: 67dba770365c
Revises: 4e0d70019bb4
Create Date: 2026-02-20 23:15:37.563913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dba770365c'
down_revision = '4e0d70019bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_ai_extractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cognitive_distortions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_ai_extractions', schema=None) as batch_op:
        batch_op.drop_column('cognitive_distortions')

    # ### end Alembic commands ###
