"""add_is_edited_to_pattern_logs

Revision ID: b05bddddfde8
Revises: 67dba770365c
Create Date: 2026-02-21 00:01:46.095008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05bddddfde8'
down_revision = '67dba770365c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pattern_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pattern_logs', schema=None) as batch_op:
        batch_op.drop_column('is_edited')

    # ### end Alembic commands ###
